Repository SurgeryWebby/Web-FrontEnd, pull requests merged in 2018-11, with the labels that each got.

#17 add font into missing part
  components/Base/Banner.js
  components/Base/TopWavySvg.js
  components/Base/WavyBannerSvg.js
  components/Base/base.css
  components/blogs/BlogItem.js
  components/blogs/BlogRightSideContent.js
  components/blogs/RelatedBlogItem.js
  components/blogs/blog/BlogContent.js
  components/blogs/blog/BlogRightSideContent.js
  components/blogs/blog/SocialButtonGroup.js
  pages/blogs/index.js
Labels: Ready To Review

#24 Feature/add unit test framework 2
  .babelrc
  .gitignore
  .nowignore
  now.json
  package-lock.json
  package.json
  src/main/about/index.js
  src/main/about/indexV2.js
  src/main/blogs/index.js
  src/main/common/Banner.js
  src/main/common/TopWavySvg.js
  src/main/common/WavyBannerSvg.js
  src/main/common/banner/base.css
  src/main/faqs/index.js
  src/main/home/index.js
  test/.eslintrc.json
  test/lib/mocha.opts
  test/lib/mocha.setup.js
  test/main/common/TopWavySvg.spec.js
  test/main/common/WavyBannerSvg.spec.js
Labels: Ready To Merge, Ready To Review

#26 [63] Refactor Menu bar
  package-lock.json
  package.json
  src/main/common/Layout.js
  src/main/menu/Language.js
  src/main/menu/LogInMenu.js
  src/main/menu/NavigationMenu.js
  src/main/menu/NavigationMenuItems.js
  src/main/menu/PhoneAndFB.js
  src/main/menu/TopMenu.js
  src/main/menu/index.js
  src/main/menu/menu.js
  src/pages/about.js
  src/pages/blog.js
  src/pages/blogs/index.js
  src/pages/faqs.js
  src/pages/index.js
  test/lib/mocha.opts
  test/main/menu/Language.spec.js
  test/main/menu/LogInMenu.spec.js
  test/main/menu/PhoneAndFB.spec.js
  test/main/menu/TopMenu.spec.js
  test/main/menu/index.spec.js
Labels: DO NOT MERGE

#31 Update now.json to use @now/next
  .gitignore
  .nowignore
  client/.dockerignore
  client/.eslintignore
  client/.gitignore
  client/Dockerfile
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/about.js
  client/pages/blog.js
  client/pages/blogs/index.js
  client/pages/faqs.js
  client/pages/index.js
  client/static/images/about/banner-background.png
  client/static/images/about/header-background.png
  client/static/images/about/service-background.png
  client/static/images/about/video.png
  client/static/images/about/whyus.png
  client/static/images/about/whyus2.png
  client/static/images/blog/cover.png
  client/static/images/blog/relatedBlogs.png
  client/static/images/blogs/blogCover.png
  client/static/images/faqs/banner.png
  client/static/images/faqs/bg.png
  client/static/images/faqs/shell.png
  client/static/images/home/banner-background.png
  client/static/images/home/banner-overlay-background.png
  client/static/images/home/banner-pagination-left.png
  client/static/images/home/banner-pagination-right.png
  client/static/images/home/banner.png
  client/static/images/home/blog-image.png
  client/static/images/home/promotion-blog-background-overlay.png
  client/static/images/home/promotion-blog-background.png
  client/static/images/home/promotion-header-overlay-background.png
  client/static/images/home/service-background.png
  client/static/images/home/service-content-background.png
  client/static/images/home/service-content-element.png
  client/static/images/menu/logo.png
  now.json
Labels: DO NOT MERGE, Ready To Merge
